### ISSUE TITLE
How to set the color of the current day or selected day? 

### ISSUE THREAD

**Issue by Sanney** [laserwave/Android-CalendarView#2]
in fact, we need to set a color for the current day or the selected day. but you have not the method.
I need your help, please

**Comment by laserwave** [comment]
hi, it is quite simple to add, I will consider adding what you have mentioned.

**Comment by laserwave** [comment]
i have updated it， check whether it satisfies your need

**Comment by Sanney** [comment]
Cool，that is exactly what I want.
Thank you very much.
